<option value="Alaska">AK - Alaska</option>
<option value="Arizona">AZ - Arizona</option>
<option value="Arkansas">AR - Arkansas</option>
<option value="California">CA - California</option>
<option value="Colorado">CO - Colorado</option>
<option value="Connecticut">CT - Connecticut</option>
<option value="Delaware">DE - Delaware</option>
<option value="District of Columbia">DC - District of Columbia</option>
<option value="Florida">FL - Florida</option>
<option value="Georgia">GA - Georgia</option>
<option value="Hawaii">HI - Hawaii</option>
<option value="Idaho">ID - Idaho</option>
<option value="Illinois">IL - Illinois</option>
<option value="Indiana">IN - Indiana</option>
<option value="Iowa">IA - Iowa</option>
<option value="Kansas">KS - Kansas</option>
<option value="Kentucky">KY - Kentucky</option>
<option value="Louisiana">LA - Louisiana</option>
<option value="Maine">ME - Maine</option>
<option value="Maryland">MD - Maryland</option>
<option value="Massachussetts">MA - Massachussetts</option>
<option value="Michigan">MI - Michigan</option>
<option value="Minnesota">MN - Minnesota</option>
<option value="Mississippi">MS - Mississippi</option>
<option value="Missouri">MO - Missouri</option>
<option value="Montana">MT - Montana</option>
<option value="Nebraska">NE - Nebraska</option>
<option value="Nevada">NV - Nevada</option>
<option value="New Hampshire">NH - New Hampshire</option>
<option value="New Jersey">NJ - New Jersey</option>
<option value="New Mexico">NM - New Mexico</option>
<option value="New York">NY - New York</option>
<option value="North Carolina">NC - North Carolina</option>
<option value="North Dakota">ND - North Dakota</option>
<option value="Ohio">OH - Ohio</option>
<option value="Oklahoma">OK - Oklahoma</option>
<option value="Oregon">OR - Oregon</option>
<option value="Pennsylvania">PA - Pennsylvania</option>
<option value="Rhode Island">RI - Rhode Island</option>
<option value="South Carolina">SC - South Carolina</option>
<option value="South Dakota">SD - South Dakota</option>
<option value="Tennessee">TN - Tennessee</option>
<option value="Texas">TX - Texas</option>
<option value="Utah">UT - Utah</option>
<option value="Vermont">VT - Vermont</option>
<option value="Virginia">VA - Virginia</option>
<option value="Washington">WA - Washington</option>
<option value="West Virginia">WV - West Virginia</option>
<option value="Wisconsin">WI - Wisconsin</option>
<option value="Wyoming">WY - Wyoming</option>